version: "3.7"
services:

  balancer-envoy:
    image: prakasa1904/envoy-error-fallback
    restart: always
    command: "/usr/local/bin/envoy -c /balancer-envoy.yaml --service-cluster balancer-proxy"
    volumes:
      - ./tokopedia.com.pem:/etc/tokopedia.com.pem
      - ./envoy/balancer-envoy.yaml:/balancer-envoy.yaml
      - ./tokopedia.com-key.pem:/etc/tokopedia.com-key.pem
    networks:
      - envoymesh
    expose:
      - "8443"
      - "8001"
    ports:
      - "443:8443"
      - "8001:8001"
    environment: 
      - ENVOY_UID=0

  frontend-http1:
    image: prakasa1904/go-http1
    restart: always
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=frontend-http1
      - BACKEND_API=http://l2-envoy
    expose:
      - "8081"

  l2-envoy:
    image: prakasa1904/envoy-error-fallback
    restart: always
    command: "/usr/local/bin/envoy -c /L2-envoy.yaml --service-cluster l2-proxy"
    volumes:
      - ./envoy/L2-envoy.yaml:/L2-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8002"
    ports:
      - "80:80"
      - "8002:8002"
    environment: 
      - ENVOY_UID=0

  backend-http1:
    image: prakasa1904/go-http1
    restart: always
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=backend-http1
    expose:
      - "8081"
  
  backend-http2:
    image: prakasa1904/go-http2
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=backend-http2
    expose:
      - "8080"

networks:
  envoymesh: {}