version: "3.7"
services:

  balancer-envoy:
    image: prakasa1904/envoy-error-fallback
    restart: always
    command: "/usr/local/bin/envoy -c /balancer-envoy.yaml --service-cluster balancer-proxy"
    volumes:
      - ./tokopedia.com.pem:/etc/tokopedia.com.pem
      - ./envoy/balancer-envoy.yaml:/balancer-envoy.yaml
      - ./tokopedia.com-key.pem:/etc/tokopedia.com-key.pem
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
    environment: 
      - ENVOY_UID=0

  ares:
    image: prakasa1904/go-http2
    restart: always
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=ares
    expose:
      - "8080"

  atreus:
    image: prakasa1904/go-http2
    restart: always
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=atreus
    expose:
      - "8080"
  
  thor:
    image: prakasa1904/go-http2
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=thor
    expose:
      - "8080"

networks:
  envoymesh: {}